{
 "title": "Backend overview",
 "tags": [
  "Backend",
  "FastAPI"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\r\n  rate(\r\n    {logger=\"fastapi-logger\"}\r\n    | json\r\n  [1m])\r\n)"
    }
   ]
  },
  {
   "title": "Логи",
   "type": "logs",
   "gridPos": { "h": 22, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{logger=\"fastapi-logger\"}\r\n| json\r\n| line_format `{{.method}} {{.path}} -> {{.status_code}} ({{.duration_ms}} ms)`"
    }
   ]
  },
  {
   "title": "Среднее время выполнения логов",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(\r\n  10,\r\n  avg by (route) (\r\n    avg_over_time(\r\n      {logger=\"fastapi-logger\"}\r\n      | json\r\n      | label_format route=\"{{.method}} {{.path}}\"\r\n      | unwrap duration_ms\r\n    [5m])\r\n  )\r\n)"
    }
   ]
  }
 ]
}